[package]
name = "prism-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prism-crypto = { workspace = true }
prism-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
